[workspace]
resolver = "2"

members = ["day-*"]

[workspace.dependencies]
divan = "0.1.3"
anyhow = "1.0.75"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
rayon = "1.8.0"
itertools = "0.12.0"
tracing-test = "0.2.4"
